title: Hello, I'm David
author:
  name: David Hason
  email: david.hason@outlook.com
description: > # this means to ignore newlines until "show_excerpts:"
Welcome to my home page I'm based in Sydney, Australia and run a small business CellCo.com in here. When I’m not running and overseeing that, I’m focusing on my true passion right here at Cellco company. 
I’ve been fortunate to have as a professional freelance data analyst and business owner. 
I specialize in artificial intelligence, machine learning, and data visualization, and regularly write about my latest work on my personal blog. 
If you'd like to talk data, ask about one of my projects, hire me to consult on a project, or anything else, please feel free to contact me by email. 
I'm glad you are here. I plan to talk about ... 
</body>

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    rss: rss
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
